# ============================================================
#   core/event_model.py — Standardized event + alert schema
# ============================================================

from dataclasses import dataclass, field, asdict
from datetime import datetime
from typing import Optional
import uuid


@dataclass
class SecurityEvent:
    """Normalized security event from any log source."""
    event_id    : str
    source      : str           # sysmon | winevent | network
    category    : str           # process | login | network | registry | file
    timestamp   : str           = field(default_factory=lambda: datetime.utcnow().isoformat())
    hostname    : str           = "WORKSTATION-01"
    username    : str           = ""
    process_name: str           = ""
    process_id  : int           = 0
    parent_proc : str           = ""
    command_line: str           = ""
    src_ip      : str           = ""
    dst_ip      : str           = ""
    dst_port    : int           = 0
    file_path   : str           = ""
    registry_key: str           = ""
    raw         : dict          = field(default_factory=dict)
    uid         : str           = field(default_factory=lambda: str(uuid.uuid4())[:8])

    def to_dict(self):
        return asdict(self)


@dataclass
class Alert:
    """Security alert generated by a detection rule."""
    alert_id     : str          = field(default_factory=lambda: str(uuid.uuid4())[:12])
    timestamp    : str          = field(default_factory=lambda: datetime.utcnow().isoformat())
    title        : str          = ""
    description  : str          = ""
    severity     : str          = "LOW"       # LOW | MEDIUM | HIGH | CRITICAL
    risk_score   : int          = 0
    detection    : str          = ""          # rule name
    mitre_id     : str          = ""
    mitre_tactic : str          = ""
    hostname     : str          = ""
    username     : str          = ""
    source_events: list         = field(default_factory=list)
    recommended  : str          = ""
    auto_response: str          = ""

    def to_dict(self):
        return asdict(self)

    @staticmethod
    def severity_from_score(score: int) -> str:
        if score >= 90: return "CRITICAL"
        if score >= 70: return "HIGH"
        if score >= 40: return "MEDIUM"
        return "LOW"
